<?php
require_once '../db.php';
require_once '../auth.php';
require_login();

$id = (int)($_GET['id'] ?? 0);
if ($id <= 0) {
    die("Invalid payment ID");
}

$sql = "
SELECT p.*, 
       b.id AS bill_id, b.billing_year, b.billing_month, b.total_amount,
       c.customer_code, c.full_name, c.address, c.phone,
       m.meter_number,
       u.name AS utility_name
FROM payments p
JOIN bills b     ON b.id = p.bill_id
JOIN customers c ON c.id = b.customer_id
JOIN meters m    ON m.id = b.meter_id
JOIN utilities u ON u.id = m.utility_id
WHERE p.id = {$id}
LIMIT 1
";

$res = $mysqli->query($sql);
$pay = $res ? $res->fetch_assoc() : null;

if (!$pay) {
    die("Payment not found");
}
?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Payment Receipt #<?= htmlspecialchars($pay['id']) ?></title>
  <link rel="stylesheet" href="../assets/css/bootstrap.min.css">

  <style>
    body { 
        padding: 30px; 
        font-family: 'Segoe UI', Tahoma, sans-serif; 
        background:#f5f6f7;
    }

    .receipt-box {
        max-width: 750px;
        margin: auto;
        background: #fff;
        padding: 35px 40px;
        border-radius: 8px;
        border: 1px solid #e1e1e1;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    }

    .header-line {
        display:flex;
        justify-content:space-between;
        align-items:center;
        border-bottom: 2px solid #333;
        padding-bottom: 12px;
        margin-bottom: 20px;
    }

    h4 {
        font-weight: 600;
        margin: 0;
        letter-spacing: 0.5px;
    }

    .section-title {
        font-size: 15px;
        font-weight: 600;
        margin-top: 25px;
        padding-bottom: 5px;
        border-bottom: 1px solid #ddd;
        color:#222;
    }

    table th {
        width: 40%;
        background: #fafafa;
        font-weight: 500;
    }

    .footer-note {
        font-size: 12px;
        color:#555;
        margin-top: 25px;
        text-align:center;
        line-height: 1.5;
    }

  </style>
</head>
<body onload="window.print()">

<div class="receipt-box">

  <div class="header-line">
    <h4>Utility Payment Receipt</h4>
    <div style="text-align:right; font-size:14px;">
      <strong>Receipt #:</strong> <?= htmlspecialchars($pay['id']) ?><br>
      <strong>Date:</strong> <?= htmlspecialchars($pay['payment_date']) ?>
    </div>
  </div>

  <!-- CUSTOMER DETAILS -->
  <div class="section-title">Customer Information</div>
  <p class="mb-2" style="font-size:14px;">
    <strong><?= htmlspecialchars($pay['customer_code'].' - '.$pay['full_name']) ?></strong><br>
    <?= nl2br(htmlspecialchars($pay['address'] ?? '')) ?><br>
    Phone: <?= htmlspecialchars($pay['phone'] ?? '') ?>
  </p>

  <!-- BILL DETAILS -->
  <div class="section-title">Bill & Meter Details</div>
  <p class="mb-2" style="font-size:14px;">
    <strong>Bill #: </strong><?= htmlspecialchars($pay['bill_id']) ?><br>
    <strong>Billing Month: </strong><?= htmlspecialchars($pay['billing_year'].'-'.$pay['billing_month']) ?><br>
    <strong>Utility: </strong><?= htmlspecialchars($pay['utility_name']) ?><br>
    <strong>Meter No: </strong><?= htmlspecialchars($pay['meter_number']) ?><br>
    <strong>Total Bill Amount: </strong>Rs. <?= number_format($pay['total_amount'],2) ?>
  </p>

  <!-- PAYMENT DETAILS -->
  <div class="section-title">Payment Summary</div>
  <table class="table table-bordered w-100 mb-3" style="font-size:14px;">
    <tr>
      <th>Amount Paid</th>
      <td><strong>Rs. <?= number_format($pay['amount'],2) ?></strong></td>
    </tr>
    <tr>
      <th>Payment Method</th>
      <td><?= htmlspecialchars($pay['method']) ?></td>
    </tr>
    <tr>
      <th>Reference No</th>
      <td><?= htmlspecialchars($pay['reference_no'] ?: '-') ?></td>
    </tr>
  </table>

  <p class="footer-note">
    This receipt is generated by the <strong>Utility Management System</strong>.<br>
    No physical signature is required.
  </p>

</div>

</body>
</html>
